export const DUMMY_REQUEST = 'DUMMY_REQUEST';
export const DUMMY_SUCCESS = 'DUMMY_SUCCESS';
export const DUMMY_FAILED = 'DUMMY_FAILED';

export const NEXT_REQUEST = 'NEXT_REQUEST';
export const NEXT_SUCCESS = 'NEXT_SUCCESS';
export const NEXT_FAILED = 'NEXT_SUCCESS';

export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILED = 'USERS_FAILED';

export const USER_PROPS_REQUEST = 'USER_PROPS_REQUEST';
export const USER_PROPS_SUCCESS = 'USER_PROPS_SUCCESS';
export const USER_PROPS_FAILED = 'USER_PROPS_FAILED';

